### ISSUE TITLE
Can't resize signal view panel after expanding it to take full space

### ISSUE THREAD

**Issue by Kristopher38** [tilk/digitaljs_online#17]
If the signal view panel gets fully expanded, it can't be resized anymore.
Steps to repro:
1. Synthesize any circuit
2. Expand the signal view panel upwards, so that it takes up full available space (code and circuit view shouldn't be visible)
3. Highlighted gray area doesn't respond to dragging anymore - on hover the cursor changes to reflect that the panel is resizeable, but when actually trying to drag it, the cursor reverts to the default state
![image](https://user-images.githubusercontent.com/11410067/119383670-e9ace980-bcc3-11eb-882d-2d7b7f520762.png)

**Comment by tilk** [comment]
Seems to work fine now.
