### ISSUE TITLE
Is there any service in the back end?

### ISSUE THREAD

**Issue by jsj613** [tilk/digitaljs_online#3]
In the webpack.config, it used a proxy. Would you please make me clear what services should be run in the back end?
Please help,thanks.
> devServer: {
>         port: 3000,
>         open: true,
>         proxy: {
>             "/api": "http://localhost:8080"
>         }

**Comment by tilk** [comment]
This is an open-source project developed in spare time. I provide the sources in the hope of them being useful, but I don't provide support.
