### ISSUE TITLE
Uncaught TypeError: Failed to execute 'readAsText' ...

### ISSUE THREAD

**Issue by hvwyl** [tilk/digitaljs_online#45]
Opening the file for the first time is ok,but if you click "Load from file" for the second time and then cancel,it will raise error "Uncaught TypeError: Failed to execute 'readAsText' ..."

the way to fix:modify the file "src/client/index.js" at line 531

```
$('#input_load').change(e => {
    const files = e.target.files;
    if (!files) return;
    const reader = new FileReader();
    destroycircuit();
    reader.onload = (e) => {
        mkcircuit(JSON.parse(e.target.result));
    };
    reader.readAsText(files[0]);
    e.target.value=''; //clear the form after loaded circuit each time
});
```

**Comment by tilk** [comment]
Can't reproduce the issue.
