### ISSUE TITLE
Questions: options and the waveform

### ISSUE THREAD

**Issue by ttnt-1013** [tilk/digitaljs_online#49]
Hi,

I'd like to ask some questions for my understanding.

- Do you have some documents of the detail of these options?
![image](https://user-images.githubusercontent.com/47150169/208011118-06b1ebe0-8c74-4bca-ab9c-12e5a6f3ea2e.png)

- Are there any ways to search wire or reg in the diagram generated by .v codes? (Is clicking blue lens button the only way to add wires to see their status at waveform area?)

Thank you for your great work!

**Comment by tilk** [comment]
* If you don't understand what these options do, you can use the defaults. In short:
  * Layout engine decides how the circuits are drawn. Switch to the other one and you'll see. The new (default) one is generally better.
  * Simulation engine is the algorithm which simulates the circuits. The new (default) one is generally better.
  * FSM transform recognizes FSMs in the circuit and performs various transformations. Load the finite state machine example to see what it does.
* Yes, the blue lens is currently the only way to achieve what you want. If you don't like it, I'm accepting pull requests.

Also, this is an issue tracker, not a discussion forum, so I'm closing the issue now.
