### ISSUE TITLE
website not working

### ISSUE THREAD

**Issue by thuvasooriya** [tilk/digitaljs_online#61]
https://digitaljs.tilk.eu/#
not working for the last two days.
not sure what happened. when you try to run a module it loads and never work.

**Comment by tilk** [comment]
In some conditions the daemon stops responding, I didn't figure out the cause. Restarted, should work fine now.

**Comment by thuvasooriya** [comment]
great. thanks. was trying for the last two days. cause an exam is coming up. thankyou for building this. sorry for the ping
